DHT republish
bitfinexcom/hypercore-logs pull request #19
Opened 2022-04-14 16:37 UTC by vitaliystoliarovcc

2022-04-22 12:29 UTC, vigan-abd reviewed
added few minor comments

2022-04-22 12:29 UTC, vigan-abd commented on src/files-watcher.js
> +        this.emit('data', line) // republish new files
should we emit also `file` here?

2022-04-22 12:29 UTC, vigan-abd commented on src/hyperswarm-dht-logger.js
> +    this.storage = []
is this used somewhere?

2022-04-22 12:29 UTC, vigan-abd commented on src/hyperswarm-dht-logger.js
> +      if (options.include && !data.match(options.include)) return false
did we setup these to on yargs?

2022-04-23 11:52 UTC, vigan-abd approved these changes
lgtm

2022-04-23 12:20 UTC, vigan-abd requested changes
these tests are failing in my env, can we check them please?
```
 1) *** Unit testing! ***
       DHT logger tests
         logger should push data to the reader:

      AssertionError: expected +0 to equal 2
      + expected - actual

      -0
      +2
      
      at Context.<anonymous> (test/dht-logger.test.js:55:37)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  2) *** Unit testing! ***
       DHT logger tests
         filter logs by date:

      AssertionError: expected [] to deeply equal [ …(3) ]
      + expected - actual

      -[]
      +[
      +  "1970-01-01T00:10:00.000Z some data"
      +  "1970-01-01T00:20:00.000Z some data"
      +  "1970-01-01T00:30:00.000Z some data"
      +]
      
      at Context.<anonymous> (test/dht-logger.test.js:162:27)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  3) *** Unit testing! ***
       logger cli
         "after each" hook for "should print the logs":
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/vigan/Desktop/bitfinex/hypercore-logs/test/index.test.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

2022-04-25 10:50 UTC, vigan-abd reviewed
@vitaliystoliarovcc now getting tests failing with randon order
```
1) *** Unit testing! ***
       DHT logger tests
         filter logs by date - startDate option:

      AssertionError: expected [ …(5) ] to deeply equal [ …(4) ]
      + expected - actual

       [
         "1970-01-01T00:20:00.000Z some data"
      -  "1970-01-01T00:10:00.000Z some data"
         "1970-01-01T00:30:00.000Z some data"
         "1970-01-01T00:40:00.000Z some data"
         "1970-01-01T00:50:00.000Z some data"
       ]
      
      at Context.<anonymous> (test/dht-logger.test.js:233:27)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  2) *** Unit testing! ***
       DHT logger tests
         filter logs by date - endDate option:

      AssertionError: expected [ …(4) ] to deeply equal [ …(4) ]
      + expected - actual

       [
      +  "1970-01-01T00:00:00.000Z some data"
         "1970-01-01T00:10:00.000Z some data"
         "1970-01-01T00:20:00.000Z some data"
         "1970-01-01T00:30:00.000Z some data"
      -  "1970-01-01T00:00:00.000Z some data"
       ]
      
      at Context.<anonymous> (test/dht-logger.test.js:270:27)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

2022-04-25 10:53 UTC, vitaliystoliarovcc commented
Ok, I'll try to increase delays

2022-04-25 11:25 UTC, vitaliystoliarovcc commented
@vigan-abd done

2022-04-27 12:08 UTC, vigan-abd approved these changes

2022-04-27 12:09 UTC, merged